#!/bin/sh

function get_pipeline() {
   export SEQ_PRISMS_BIN=/dataset/gseq_processing/active/bin/resequencing_prism/seq_prisms 
   export RESEQUENCING_PRISM_BIN=/dataset/gseq_processing/active/bin/resequencing_prism
   cd $RESEQUENCING_PRISM_BIN 
   resequencing_version=$1
   echo "preparing to run pipeline version $resequencing_version (press enter to continue)"
   read answer
   is_alpha=`echo $resequencing_version | grep alpha`
   if [ ! $is_alpha ]; then 
      git checkout -q $resequencing_version  
      if [ $? != 0 ]; then
         echo "unable to checkout pipeline version $resequencing_version"
         exit 1
      fi
      exec ./_reseq $resequencing_version
   else
      echo "(no checkout for alpha versions, just running in current branch)"
      exec ./_reseq $resequencing_version 
   fi
}

get_pipeline v0.0.1-alpha
